#!/bin/bash

#### These are the parameters used for submitting the script to the department cluster queue
#$ -R y
###reserving the memory specified
#$ -l h_vmem=5G
###requirement for the memory
#$ -cwd
###current working directory
#$ -m beas
###sending email updates


######################################
# Pro-0 x Est-1 mapping (run154_lane1)
######################################

##### where all the samples are
WD=/ebio/abt6_projects8/ACD6_suppressors/data/run154_lane1-8

##### sample directory
LANE1=/ebio/abt6_projects8/ACD6_suppressors/data/run154_lane1-8/run154_1/1


#################################################################################################################
## 1) Remove the 1st column for chromosome number, and incorporate it with the POS column
## 2) For the quality variant file: Filter the SNP list by removing the mitochondrial and chloroplast DNA SNPs
## 3) For the quality variant file: Filter the SNP list by removing the deletions
## 4) For the quality variant file: Filter the SNP list by keeping non-repetitive mapping reads
## 5) After filtering merge the qv and qr SNP list keeping the qv SNPs that are not in the qr SNP list file
## ----We need to delete those rows from main.txt for which the id field (1st field) has an entry in subfile.txt.
## ----$ awk 'NR==FNR{A[$1];next}!($1 in A)' FS=: subfile.txt main.txt
## ----So, associative array named A is created with the Ids of 1st processed file (subfile.txt, for which NR==FNR, as it is first in the sequence "subfile.txt main.txt" above).
## 6) After step 5, merge the qv and qr SNP lists
#################################################################################################################

###################
##### run154_LANE1 #######
###################

for pt in 1 2
do
for rn in A B C D E F G H
do
for cn in 01 02 03 04 05 06 07 08 09 10 11 12
do

awk '{if ($2<6 && $5!="-" && $9==1) print $2*100000000+$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9}' $LANE1/sample_P$pt$rn$cn/Analysis/ConsensusAnalysis/quality_variant.txt > $LANE1/run154_1_P$pt$rn$cn.qv

### only to use for non unxz files ####
unxz $LANE1/sample_P$pt$rn$cn/Analysis/ConsensusAnalysis/quality_reference.txt.xz 

awk '{if ($2<6 && $6>24) print $2*100000000+$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9}' $LANE1/sample_P$pt$rn$cn/Analysis/ConsensusAnalysis/quality_reference.txt > $LANE1/run154_1_P$pt$rn$cn.qr

awk 'FNR==NR{a[$1];next} (!($1 in a))' $LANE1/run154_1_P$pt$rn$cn.qv $LANE1/run154_1_P$pt$rn$cn.qr > $LANE1/run154_1_P$pt$rn$cn.qr_only

cat $LANE1/run154_1_P$pt$rn$cn.qv $LANE1/run154_1_P$pt$rn$cn.qr_only | sort -g -k1 > $GTDIR/run154_1_P$pt$rn$cn.qvqr

done
done
done
